version: "3.9"

services:

  db:
    image: harbor.sahimco.ir/public/postgres:14.3.1-postgis
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=insighthub
      - POSTGRES_USER=ihub
      - POSTGRES_PASSWORD=ihub
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


  rabbitmq:
    image: harbor.sahimco.ir/public/rabbitmq:4.0.9-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: harbor.sahimco.ir/public/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
        - .:/app
    depends_on:
        - rabbitmq

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info -S django
    volumes:
        - .:/app
    depends_on:
        - rabbitmq
volumes:
    postgres-data:
    redis-data:

