# Generated by Django 4.0.7 on 2025-06-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='arguments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
