# Generated by Django 4.0.7 on 2025-06-23 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_remove_task_data_type_remove_task_entry_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskinput',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
