# Generated by Django 4.0.7 on 2025-06-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskinput_user_taskinput_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinput',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskinput',
            name='value',
        ),
    ]
